CREATE TABLE `answer_comparisons` (
	`id` varchar(128) NOT NULL,
	`userId` int NOT NULL,
	`questionNumber` int NOT NULL,
	`userSubmissionId` varchar(128) NOT NULL,
	`comparedWithSubmissionId` varchar(128),
	`noveltyGap` int,
	`coherenceGap` int,
	`rigorGap` int,
	`synthesisGap` int,
	`formalizationGap` int,
	`depthGap` int,
	`overallAnalysis` text,
	`noveltyRecommendations` text,
	`coherenceRecommendations` text,
	`rigorRecommendations` text,
	`synthesisRecommendations` text,
	`formalizationRecommendations` text,
	`depthRecommendations` text,
	`comparisonModel` varchar(50),
	`comparisonTime` int,
	`createdAt` timestamp DEFAULT (now()),
	CONSTRAINT `answer_comparisons_id` PRIMARY KEY(`id`)
);
