#!/bin/bash
# Download script for 01-ai/Yi-34B-Chat
# Generated by LLM Recovery System

echo "Downloading 01-ai/Yi-34B-Chat..."
huggingface-cli download 01-ai/Yi-34B-Chat --local-dir ./models/01-ai_Yi-34B-Chat
echo "Download complete!"
