#!/bin/bash
# Download script for BAAI/bge-base-en-v1.5
# Generated by LLM Recovery System

echo "Downloading BAAI/bge-base-en-v1.5..."
huggingface-cli download BAAI/bge-base-en-v1.5 --local-dir ./models/BAAI_bge-base-en-v1.5
echo "Download complete!"
