#!/bin/bash
# Download script for baichuan-inc/Baichuan2-7B-Chat
# Generated by LLM Recovery System

echo "Downloading baichuan-inc/Baichuan2-7B-Chat..."
huggingface-cli download baichuan-inc/Baichuan2-7B-Chat --local-dir ./models/baichuan-inc_Baichuan2-7B-Chat
echo "Download complete!"
