#!/bin/bash
# Download script for baichuan-inc/Baichuan2-13B-Chat
# Generated by LLM Recovery System

echo "Downloading baichuan-inc/Baichuan2-13B-Chat..."
huggingface-cli download baichuan-inc/Baichuan2-13B-Chat --local-dir ./models/baichuan-inc_Baichuan2-13B-Chat
echo "Download complete!"
