#!/bin/bash
# Download script for bigcode/starcoder2-15b
# Generated by LLM Recovery System

echo "Downloading bigcode/starcoder2-15b..."
huggingface-cli download bigcode/starcoder2-15b --local-dir ./models/bigcode_starcoder2-15b
echo "Download complete!"
