#!/bin/bash
# Download script for bigcode/starcoder2-7b
# Generated by LLM Recovery System

echo "Downloading bigcode/starcoder2-7b..."
huggingface-cli download bigcode/starcoder2-7b --local-dir ./models/bigcode_starcoder2-7b
echo "Download complete!"
