#!/bin/bash
# Download script for bigcode/starcoder2-3b
# Generated by LLM Recovery System

echo "Downloading bigcode/starcoder2-3b..."
huggingface-cli download bigcode/starcoder2-3b --local-dir ./models/bigcode_starcoder2-3b
echo "Download complete!"
