#!/bin/bash
# Download script for bigscience/bloom-560m
# Generated by LLM Recovery System

echo "Downloading bigscience/bloom-560m..."
huggingface-cli download bigscience/bloom-560m --local-dir ./models/bigscience_bloom-560m
echo "Download complete!"
