#!/bin/bash
# Download script for bigscience/bloom-1b7
# Generated by LLM Recovery System

echo "Downloading bigscience/bloom-1b7..."
huggingface-cli download bigscience/bloom-1b7 --local-dir ./models/bigscience_bloom-1b7
echo "Download complete!"
