#!/bin/bash
# Download script for bigscience/bloom-3b
# Generated by LLM Recovery System

echo "Downloading bigscience/bloom-3b..."
huggingface-cli download bigscience/bloom-3b --local-dir ./models/bigscience_bloom-3b
echo "Download complete!"
