#!/bin/bash
# Download script for bigscience/bloom-7b1
# Generated by LLM Recovery System

echo "Downloading bigscience/bloom-7b1..."
huggingface-cli download bigscience/bloom-7b1 --local-dir ./models/bigscience_bloom-7b1
echo "Download complete!"
