#!/bin/bash
# Download script for deepseek-ai/deepseek-coder-1.3b-instruct
# Generated by LLM Recovery System

echo "Downloading deepseek-ai/deepseek-coder-1.3b-instruct..."
huggingface-cli download deepseek-ai/deepseek-coder-1.3b-instruct --local-dir ./models/deepseek-ai_deepseek-coder-1.3b-instruct
echo "Download complete!"
