#!/bin/bash
# Download script for deepseek-ai/DeepSeek-Coder-V2-Instruct
# Generated by LLM Recovery System

echo "Downloading deepseek-ai/DeepSeek-Coder-V2-Instruct..."
huggingface-cli download deepseek-ai/DeepSeek-Coder-V2-Instruct --local-dir ./models/deepseek-ai_DeepSeek-Coder-V2-Instruct
echo "Download complete!"
