#!/bin/bash
# Download script for deepseek-ai/deepseek-math-7b-instruct
# Generated by LLM Recovery System

echo "Downloading deepseek-ai/deepseek-math-7b-instruct..."
huggingface-cli download deepseek-ai/deepseek-math-7b-instruct --local-dir ./models/deepseek-ai_deepseek-math-7b-instruct
echo "Download complete!"
