#!/bin/bash
# Download script for deepseek-ai/DeepSeek-V3
# Generated by LLM Recovery System

echo "Downloading deepseek-ai/DeepSeek-V3..."
huggingface-cli download deepseek-ai/DeepSeek-V3 --local-dir ./models/deepseek-ai_DeepSeek-V3
echo "Download complete!"
