#!/bin/bash
# Download script for deepseek-ai/DeepSeek-R1
# Generated by LLM Recovery System

echo "Downloading deepseek-ai/DeepSeek-R1..."
huggingface-cli download deepseek-ai/DeepSeek-R1 --local-dir ./models/deepseek-ai_DeepSeek-R1
echo "Download complete!"
