#!/bin/bash
# Download script for dmis-lab/biobert-v1.1
# Generated by LLM Recovery System

echo "Downloading dmis-lab/biobert-v1.1..."
huggingface-cli download dmis-lab/biobert-v1.1 --local-dir ./models/dmis-lab_biobert-v1.1
echo "Download complete!"
