#!/bin/bash
# Download script for EleutherAI/llemma_34b
# Generated by LLM Recovery System

echo "Downloading EleutherAI/llemma_34b..."
huggingface-cli download EleutherAI/llemma_34b --local-dir ./models/EleutherAI_llemma_34b
echo "Download complete!"
