#!/bin/bash
# Download script for EleutherAI/gpt-j-6b
# Generated by LLM Recovery System

echo "Downloading EleutherAI/gpt-j-6b..."
huggingface-cli download EleutherAI/gpt-j-6b --local-dir ./models/EleutherAI_gpt-j-6b
echo "Download complete!"
