#!/bin/bash
# Download script for EleutherAI/llemma_7b
# Generated by LLM Recovery System

echo "Downloading EleutherAI/llemma_7b..."
huggingface-cli download EleutherAI/llemma_7b --local-dir ./models/EleutherAI_llemma_7b
echo "Download complete!"
