#!/bin/bash
# Download script for emilyalsentzer/Bio_ClinicalBERT
# Generated by LLM Recovery System

echo "Downloading emilyalsentzer/Bio_ClinicalBERT..."
huggingface-cli download emilyalsentzer/Bio_ClinicalBERT --local-dir ./models/emilyalsentzer_Bio_ClinicalBERT
echo "Download complete!"
