#!/bin/bash
# Download script for facebook/incoder-6B
# Generated by LLM Recovery System

echo "Downloading facebook/incoder-6B..."
huggingface-cli download facebook/incoder-6B --local-dir ./models/facebook_incoder-6B
echo "Download complete!"
