#!/bin/bash
# Download script for GAIR/Abel-13B
# Generated by LLM Recovery System

echo "Downloading GAIR/Abel-13B..."
huggingface-cli download GAIR/Abel-13B --local-dir ./models/GAIR_Abel-13B
echo "Download complete!"
