#!/bin/bash
# Download script for GAIR/Abel-70B
# Generated by LLM Recovery System

echo "Downloading GAIR/Abel-70B..."
huggingface-cli download GAIR/Abel-70B --local-dir ./models/GAIR_Abel-70B
echo "Download complete!"
