#!/bin/bash
# Download script for GAIR/Abel-7B
# Generated by LLM Recovery System

echo "Downloading GAIR/Abel-7B..."
huggingface-cli download GAIR/Abel-7B --local-dir ./models/GAIR_Abel-7B
echo "Download complete!"
