#!/bin/bash
# Download script for google/codegemma-2b
# Generated by LLM Recovery System

echo "Downloading google/codegemma-2b..."
huggingface-cli download google/codegemma-2b --local-dir ./models/google_codegemma-2b
echo "Download complete!"
