#!/bin/bash
# Download script for google/codegemma-7b-it
# Generated by LLM Recovery System

echo "Downloading google/codegemma-7b-it..."
huggingface-cli download google/codegemma-7b-it --local-dir ./models/google_codegemma-7b-it
echo "Download complete!"
