#!/bin/bash
# Download script for google/gemma-2-2b-it
# Generated by LLM Recovery System

echo "Downloading google/gemma-2-2b-it..."
huggingface-cli download google/gemma-2-2b-it --local-dir ./models/google_gemma-2-2b-it
echo "Download complete!"
