#!/bin/bash
# Download script for HuggingFaceTB/SmolLM-360M-Instruct
# Generated by LLM Recovery System

echo "Downloading HuggingFaceTB/SmolLM-360M-Instruct..."
huggingface-cli download HuggingFaceTB/SmolLM-360M-Instruct --local-dir ./models/HuggingFaceTB_SmolLM-360M-Instruct
echo "Download complete!"
