#!/bin/bash
# Download script for HuggingFaceTB/SmolLM-1.7B-Instruct
# Generated by LLM Recovery System

echo "Downloading HuggingFaceTB/SmolLM-1.7B-Instruct..."
huggingface-cli download HuggingFaceTB/SmolLM-1.7B-Instruct --local-dir ./models/HuggingFaceTB_SmolLM-1.7B-Instruct
echo "Download complete!"
