#!/bin/bash
# Download script for inceptionai/jais-13b-chat
# Generated by LLM Recovery System

echo "Downloading inceptionai/jais-13b-chat..."
huggingface-cli download inceptionai/jais-13b-chat --local-dir ./models/inceptionai_jais-13b-chat
echo "Download complete!"
