#!/bin/bash
# Download script for internlm/internlm2-chat-20b
# Generated by LLM Recovery System

echo "Downloading internlm/internlm2-chat-20b..."
huggingface-cli download internlm/internlm2-chat-20b --local-dir ./models/internlm_internlm2-chat-20b
echo "Download complete!"
