#!/bin/bash
# Download script for internlm/internlm2-chat-7b
# Generated by LLM Recovery System

echo "Downloading internlm/internlm2-chat-7b..."
huggingface-cli download internlm/internlm2-chat-7b --local-dir ./models/internlm_internlm2-chat-7b
echo "Download complete!"
