#!/bin/bash
# Download script for intfloat/e5-large-v2
# Generated by LLM Recovery System

echo "Downloading intfloat/e5-large-v2..."
huggingface-cli download intfloat/e5-large-v2 --local-dir ./models/intfloat_e5-large-v2
echo "Download complete!"
