#!/bin/bash
# Download script for intfloat/e5-base-v2
# Generated by LLM Recovery System

echo "Downloading intfloat/e5-base-v2..."
huggingface-cli download intfloat/e5-base-v2 --local-dir ./models/intfloat_e5-base-v2
echo "Download complete!"
