#!/bin/bash
# Download script for liuhaotian/llava-v1.6-34b
# Generated by LLM Recovery System

echo "Downloading liuhaotian/llava-v1.6-34b..."
huggingface-cli download liuhaotian/llava-v1.6-34b --local-dir ./models/liuhaotian_llava-v1.6-34b
echo "Download complete!"
