#!/bin/bash
# Download script for liuhaotian/llava-v1.5-7b
# Generated by LLM Recovery System

echo "Downloading liuhaotian/llava-v1.5-7b..."
huggingface-cli download liuhaotian/llava-v1.5-7b --local-dir ./models/liuhaotian_llava-v1.5-7b
echo "Download complete!"
