#!/bin/bash
# Download script for liuhaotian/llava-v1.5-13b
# Generated by LLM Recovery System

echo "Downloading liuhaotian/llava-v1.5-13b..."
huggingface-cli download liuhaotian/llava-v1.5-13b --local-dir ./models/liuhaotian_llava-v1.5-13b
echo "Download complete!"
