#!/bin/bash
# Download script for lmsys/vicuna-13b-v1.5
# Generated by LLM Recovery System

echo "Downloading lmsys/vicuna-13b-v1.5..."
huggingface-cli download lmsys/vicuna-13b-v1.5 --local-dir ./models/lmsys_vicuna-13b-v1.5
echo "Download complete!"
