#!/bin/bash
# Download script for lmsys/vicuna-33b-v1.3
# Generated by LLM Recovery System

echo "Downloading lmsys/vicuna-33b-v1.3..."
huggingface-cli download lmsys/vicuna-33b-v1.3 --local-dir ./models/lmsys_vicuna-33b-v1.3
echo "Download complete!"
