#!/bin/bash
# Download script for microsoft/phi-2
# Generated by LLM Recovery System

echo "Downloading microsoft/phi-2..."
huggingface-cli download microsoft/phi-2 --local-dir ./models/microsoft_phi-2
echo "Download complete!"
