#!/bin/bash
# Download script for microsoft/Orca-2-13b
# Generated by LLM Recovery System

echo "Downloading microsoft/Orca-2-13b..."
huggingface-cli download microsoft/Orca-2-13b --local-dir ./models/microsoft_Orca-2-13b
echo "Download complete!"
