#!/bin/bash
# Download script for microsoft/Phi-3-mini-4k-instruct
# Generated by LLM Recovery System

echo "Downloading microsoft/Phi-3-mini-4k-instruct..."
huggingface-cli download microsoft/Phi-3-mini-4k-instruct --local-dir ./models/microsoft_Phi-3-mini-4k-instruct
echo "Download complete!"
