#!/bin/bash
# Download script for microsoft/Orca-2-7b
# Generated by LLM Recovery System

echo "Downloading microsoft/Orca-2-7b..."
huggingface-cli download microsoft/Orca-2-7b --local-dir ./models/microsoft_Orca-2-7b
echo "Download complete!"
