#!/bin/bash
# Download script for microsoft/Phi-3-small-8k-instruct
# Generated by LLM Recovery System

echo "Downloading microsoft/Phi-3-small-8k-instruct..."
huggingface-cli download microsoft/Phi-3-small-8k-instruct --local-dir ./models/microsoft_Phi-3-small-8k-instruct
echo "Download complete!"
