#!/bin/bash
# Download script for microsoft/BiomedNLP-PubMedBERT-base-uncased-abstract-fulltext
# Generated by LLM Recovery System

echo "Downloading microsoft/BiomedNLP-PubMedBERT-base-uncased-abstract-fulltext..."
huggingface-cli download microsoft/BiomedNLP-PubMedBERT-base-uncased-abstract-fulltext --local-dir ./models/microsoft_BiomedNLP-PubMedBERT-base-uncased-abstract-fulltext
echo "Download complete!"
