#!/bin/bash
# Download script for microsoft/BioGPT-Large
# Generated by LLM Recovery System

echo "Downloading microsoft/BioGPT-Large..."
huggingface-cli download microsoft/BioGPT-Large --local-dir ./models/microsoft_BioGPT-Large
echo "Download complete!"
