#!/bin/bash
# Download script for mistralai/Mixtral-8x7B-Instruct-v0.1
# Generated by LLM Recovery System

echo "Downloading mistralai/Mixtral-8x7B-Instruct-v0.1..."
huggingface-cli download mistralai/Mixtral-8x7B-Instruct-v0.1 --local-dir ./models/mistralai_Mixtral-8x7B-Instruct-v0.1
echo "Download complete!"
