#!/bin/bash
# Download script for mistralai/Mistral-7B-Instruct-v0.3
# Generated by LLM Recovery System

echo "Downloading mistralai/Mistral-7B-Instruct-v0.3..."
huggingface-cli download mistralai/Mistral-7B-Instruct-v0.3 --local-dir ./models/mistralai_Mistral-7B-Instruct-v0.3
echo "Download complete!"
