#!/bin/bash
# Download script for mistralai/Mistral-Large-Instruct-2407
# Generated by LLM Recovery System

echo "Downloading mistralai/Mistral-Large-Instruct-2407..."
huggingface-cli download mistralai/Mistral-Large-Instruct-2407 --local-dir ./models/mistralai_Mistral-Large-Instruct-2407
echo "Download complete!"
