#!/bin/bash
# Download script for mistralai/Codestral-22B-v0.1
# Generated by LLM Recovery System

echo "Downloading mistralai/Codestral-22B-v0.1..."
huggingface-cli download mistralai/Codestral-22B-v0.1 --local-dir ./models/mistralai_Codestral-22B-v0.1
echo "Download complete!"
