#!/bin/bash
# Download script for mosaicml/mpt-30b-chat
# Generated by LLM Recovery System

echo "Downloading mosaicml/mpt-30b-chat..."
huggingface-cli download mosaicml/mpt-30b-chat --local-dir ./models/mosaicml_mpt-30b-chat
echo "Download complete!"
