#!/bin/bash
# Download script for NousResearch/Nous-Hermes-2-Mixtral-8x7B-DPO
# Generated by LLM Recovery System

echo "Downloading NousResearch/Nous-Hermes-2-Mixtral-8x7B-DPO..."
huggingface-cli download NousResearch/Nous-Hermes-2-Mixtral-8x7B-DPO --local-dir ./models/NousResearch_Nous-Hermes-2-Mixtral-8x7B-DPO
echo "Download complete!"
