#!/bin/bash
# Download script for openchat/openchat-3.5-0106
# Generated by LLM Recovery System

echo "Downloading openchat/openchat-3.5-0106..."
huggingface-cli download openchat/openchat-3.5-0106 --local-dir ./models/openchat_openchat-3.5-0106
echo "Download complete!"
