#!/bin/bash
# Download script for Open-Orca/Mistral-7B-OpenOrca
# Generated by LLM Recovery System

echo "Downloading Open-Orca/Mistral-7B-OpenOrca..."
huggingface-cli download Open-Orca/Mistral-7B-OpenOrca --local-dir ./models/Open-Orca_Mistral-7B-OpenOrca
echo "Download complete!"
