#!/bin/bash
# Download script for Qwen/Qwen-VL-Chat
# Generated by LLM Recovery System

echo "Downloading Qwen/Qwen-VL-Chat..."
huggingface-cli download Qwen/Qwen-VL-Chat --local-dir ./models/Qwen_Qwen-VL-Chat
echo "Download complete!"
