#!/bin/bash
# Download script for Salesforce/codegen2-1B
# Generated by LLM Recovery System

echo "Downloading Salesforce/codegen2-1B..."
huggingface-cli download Salesforce/codegen2-1B --local-dir ./models/Salesforce_codegen2-1B
echo "Download complete!"
