#!/bin/bash
# Download script for Salesforce/codegen-16B-mono
# Generated by LLM Recovery System

echo "Downloading Salesforce/codegen-16B-mono..."
huggingface-cli download Salesforce/codegen-16B-mono --local-dir ./models/Salesforce_codegen-16B-mono
echo "Download complete!"
