#!/bin/bash
# Download script for Salesforce/codegen2-16B
# Generated by LLM Recovery System

echo "Downloading Salesforce/codegen2-16B..."
huggingface-cli download Salesforce/codegen2-16B --local-dir ./models/Salesforce_codegen2-16B
echo "Download complete!"
