#!/bin/bash
# Download script for Salesforce/blip2-opt-6.7b
# Generated by LLM Recovery System

echo "Downloading Salesforce/blip2-opt-6.7b..."
huggingface-cli download Salesforce/blip2-opt-6.7b --local-dir ./models/Salesforce_blip2-opt-6.7b
echo "Download complete!"
