#!/bin/bash
# Download script for Salesforce/codegen2-3_7B
# Generated by LLM Recovery System

echo "Downloading Salesforce/codegen2-3_7B..."
huggingface-cli download Salesforce/codegen2-3_7B --local-dir ./models/Salesforce_codegen2-3_7B
echo "Download complete!"
