#!/bin/bash
# Download script for sentence-transformers/all-mpnet-base-v2
# Generated by LLM Recovery System

echo "Downloading sentence-transformers/all-mpnet-base-v2..."
huggingface-cli download sentence-transformers/all-mpnet-base-v2 --local-dir ./models/sentence-transformers_all-mpnet-base-v2
echo "Download complete!"
