#!/bin/bash
# Download script for sentence-transformers/all-MiniLM-L6-v2
# Generated by LLM Recovery System

echo "Downloading sentence-transformers/all-MiniLM-L6-v2..."
huggingface-cli download sentence-transformers/all-MiniLM-L6-v2 --local-dir ./models/sentence-transformers_all-MiniLM-L6-v2
echo "Download complete!"
