#!/bin/bash
# Download script for stabilityai/stablelm-tuned-alpha-7b
# Generated by LLM Recovery System

echo "Downloading stabilityai/stablelm-tuned-alpha-7b..."
huggingface-cli download stabilityai/stablelm-tuned-alpha-7b --local-dir ./models/stabilityai_stablelm-tuned-alpha-7b
echo "Download complete!"
