#!/bin/bash
# Download script for stabilityai/stablelm-zephyr-3b
# Generated by LLM Recovery System

echo "Downloading stabilityai/stablelm-zephyr-3b..."
huggingface-cli download stabilityai/stablelm-zephyr-3b --local-dir ./models/stabilityai_stablelm-zephyr-3b
echo "Download complete!"
