#!/bin/bash
# Download script for THUDM/chatglm3-6b
# Generated by LLM Recovery System

echo "Downloading THUDM/chatglm3-6b..."
huggingface-cli download THUDM/chatglm3-6b --local-dir ./models/THUDM_chatglm3-6b
echo "Download complete!"
