#!/bin/bash
# Download script for TIGER-Lab/MAmmoTH-7B
# Generated by LLM Recovery System

echo "Downloading TIGER-Lab/MAmmoTH-7B..."
huggingface-cli download TIGER-Lab/MAmmoTH-7B --local-dir ./models/TIGER-Lab_MAmmoTH-7B
echo "Download complete!"
