#!/bin/bash
# Download script for TIGER-Lab/MAmmoTH-13B
# Generated by LLM Recovery System

echo "Downloading TIGER-Lab/MAmmoTH-13B..."
huggingface-cli download TIGER-Lab/MAmmoTH-13B --local-dir ./models/TIGER-Lab_MAmmoTH-13B
echo "Download complete!"
