#!/bin/bash
# Download script for TIGER-Lab/MAmmoTH-70B
# Generated by LLM Recovery System

echo "Downloading TIGER-Lab/MAmmoTH-70B..."
huggingface-cli download TIGER-Lab/MAmmoTH-70B --local-dir ./models/TIGER-Lab_MAmmoTH-70B
echo "Download complete!"
