#!/bin/bash
# Download script for tiiuae/falcon-180B
# Generated by LLM Recovery System

echo "Downloading tiiuae/falcon-180B..."
huggingface-cli download tiiuae/falcon-180B --local-dir ./models/tiiuae_falcon-180B
echo "Download complete!"
