#!/bin/bash
# Download script for tiiuae/falcon-7b-instruct
# Generated by LLM Recovery System

echo "Downloading tiiuae/falcon-7b-instruct..."
huggingface-cli download tiiuae/falcon-7b-instruct --local-dir ./models/tiiuae_falcon-7b-instruct
echo "Download complete!"
