#!/bin/bash
# Download script for timdettmers/guanaco-7b
# Generated by LLM Recovery System

echo "Downloading timdettmers/guanaco-7b..."
huggingface-cli download timdettmers/guanaco-7b --local-dir ./models/timdettmers_guanaco-7b
echo "Download complete!"
