#!/bin/bash
# Download script for timdettmers/guanaco-65b
# Generated by LLM Recovery System

echo "Downloading timdettmers/guanaco-65b..."
huggingface-cli download timdettmers/guanaco-65b --local-dir ./models/timdettmers_guanaco-65b
echo "Download complete!"
