#!/bin/bash
# Download script for timdettmers/guanaco-13b
# Generated by LLM Recovery System

echo "Downloading timdettmers/guanaco-13b..."
huggingface-cli download timdettmers/guanaco-13b --local-dir ./models/timdettmers_guanaco-13b
echo "Download complete!"
