#!/bin/bash
# Download script for timdettmers/guanaco-33b
# Generated by LLM Recovery System

echo "Downloading timdettmers/guanaco-33b..."
huggingface-cli download timdettmers/guanaco-33b --local-dir ./models/timdettmers_guanaco-33b
echo "Download complete!"
