#!/bin/bash
# Download script for UFNLP/gatortron-base
# Generated by LLM Recovery System

echo "Downloading UFNLP/gatortron-base..."
huggingface-cli download UFNLP/gatortron-base --local-dir ./models/UFNLP_gatortron-base
echo "Download complete!"
