#!/bin/bash
# Download script for WizardLM/WizardMath-13B-V1.0
# Generated by LLM Recovery System

echo "Downloading WizardLM/WizardMath-13B-V1.0..."
huggingface-cli download WizardLM/WizardMath-13B-V1.0 --local-dir ./models/WizardLM_WizardMath-13B-V1.0
echo "Download complete!"
