#!/bin/bash
# Download script for WizardLM/WizardCoder-15B-V1.0
# Generated by LLM Recovery System

echo "Downloading WizardLM/WizardCoder-15B-V1.0..."
huggingface-cli download WizardLM/WizardCoder-15B-V1.0 --local-dir ./models/WizardLM_WizardCoder-15B-V1.0
echo "Download complete!"
