#!/bin/bash
# Download script for WizardLM/WizardLM-7B-V1.0
# Generated by LLM Recovery System

echo "Downloading WizardLM/WizardLM-7B-V1.0..."
huggingface-cli download WizardLM/WizardLM-7B-V1.0 --local-dir ./models/WizardLM_WizardLM-7B-V1.0
echo "Download complete!"
