#!/bin/bash
# Download script for WizardLM/WizardLM-13B-V1.2
# Generated by LLM Recovery System

echo "Downloading WizardLM/WizardLM-13B-V1.2..."
huggingface-cli download WizardLM/WizardLM-13B-V1.2 --local-dir ./models/WizardLM_WizardLM-13B-V1.2
echo "Download complete!"
