#!/bin/bash
# Download script for WizardLM/WizardCoder-33B-V1.1
# Generated by LLM Recovery System

echo "Downloading WizardLM/WizardCoder-33B-V1.1..."
huggingface-cli download WizardLM/WizardCoder-33B-V1.1 --local-dir ./models/WizardLM_WizardCoder-33B-V1.1
echo "Download complete!"
